### ISSUE TITLE
Two sided tree search.

### ISSUE THREAD

**Issue by maxi4r** [FjellOverflow/rubiks-solver#1]
One trick to reduce the computational costs for finding a new solution would be to not only perform a tree search for the state of the scrambled cube. Instead, one could employ a second tree search using the solved cube as root and search for the first pair of leaves, i.e. states, that match. That allows exploring more depth without growing as fast in width.

**Comment by FjellOverflow** [comment]
That is indeed a very neat idea! I encourage you to open up a PR ;-)
